### ISSUE TITLE
Обновление `Commander` в генераторах

### ISSUE THREAD

**Issue by Amiditin** [atls/hyperion#573]
### С чем связан запрос на фичу?

Необходимо обновить пакет `commander` в генераторах под esm

### Расскажите как вы это себе видите

- [ ] бамп `commander` до последней версии `12.1.0`

### Definition of done (критерий готовности)

Пакет `commander` обновлён, команды генераторов выполняются без ошибок 

### Источник

https://github.com/rees46/planning/issues/1498#issuecomment-2332241685

**Comment by Amiditin** [comment]
@Nelfimov обновил "commander" до "12.1.0", всё равно выдаёт ошибку:
```
amiditin@amiditin-B550M-AORUS-PRO-P:~/React/hyperion$ yarn workspace @atls-ui-generators/button generate-styles src/styles.ts -t src/colors.ts
undefined:3
Object.defineProperty(exports, "__esModule", {
                      ^

ReferenceError: exports is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/home/amiditin/React/hyperion/generators/button/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at eval (eval at <anonymous> (file:///home/amiditin/React/hyperion/generators/button/dist/generator.js:17:20), <anonymous>:3:23)
    at Command.<anonymous> (file:///home/amiditin/React/hyperion/generators/button/dist/generator.js:17:20)
    at Command.listener [as _actionHandler] (/home/amiditin/React/.yarn/berry/cache/commander-npm-12.1.0-65c868e907-10.zip/node_modules/commander/lib/command.js:542:17)
    at /home/amiditin/React/.yarn/berry/cache/commander-npm-12.1.0-65c868e907-10.zip/node_modules/commander/lib/command.js:1502:14
    at Command._chainOrCall (/home/amiditin/React/.yarn/berry/cache/commander-npm-12.1.0-65c868e907-10.zip/node_modules/commander/lib/command.js:1386:12)
    at Command._parseCommand (/home/amiditin/React/.yarn/berry/cache/commander-npm-12.1.0-65c868e907-10.zip/node_modules/commander/lib/command.js:1501:27)
    at Command.parse (/home/amiditin/React/.yarn/berry/cache/commander-npm-12.1.0-65c868e907-10.zip/node_modules/commander/lib/command.js:1064:10)
    at file:///home/amiditin/React/hyperion/generators/button/dist/generator.js:23:9
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5)

Node.js v20.16.0
```
Как пишет проблема в `eval` функции [file](https://github.com/atls/hyperion/blob/73de7540cb61c57113973b0407f44449e0db4a63/generators/button/src/generator.ts#L22), если её убрать (заменить на код), то генератор сработает. Пока способ пофиксить или альтернативы `eval` не нашел, есть идеи что можно попробовать?

**Comment by Nelfimov** [comment]
@Amiditin нужно конкретно генератор переводить в .cjs. Тут сделал рабочий прототип:

https://github.com/rees46/web-app/commit/963b3ada1c5229c676e0350541a0cf1356d6f103

Пока другого способа не придумал. Можно посмотреть вглубь и выяснить почему где-то в билде берется `exports`. Возможно имеет смысл вебпак перенастроить.
